### ISSUE TITLE
Can't find engine and client module

### ISSUE THREAD

**Issue by tworkool** [ToKKaN/better-external-backtrack#2]
Hey, I wanted to test your backtrack but it seems that the modules engine.dll and client_panorama.dll cant be found. When debugging it shows only the following modules: 
![debug](https://user-images.githubusercontent.com/55762879/67422348-9730b600-f5d2-11e9-909f-91aa5a693b45.PNG)
Do you know how to fix this? was this an issue in the past?

**Comment by ToKKaN** [comment]
Try to start the game first and then the Cheat

**Comment by tworkool** [comment]
Sadly does not work. Even after haphazardly adding my own class for getting the modules it didn't find the modules somehow. Have to get into it a bit deeper when I have time.

**Comment by ToKKaN** [comment]
If you use your own Class this issue page is not the right place. You probably have some privilege issue

**Comment by tworkool** [comment]
sry maybe I miswrote, but the issue was there before. I tried to fix it or atleast figure out what the problem wis by adding my own base

**Comment by ToKKaN** [comment]
Yeah but the code was tested and working so I assume you have a privilege issue and your application simply can not access the CS:GO process because your own class isnt working aswell. This hints to a privilege issue. Maybe your Visual Studio is not started as admin or something

**Comment by tworkool** [comment]
Ok thanks for the tip.
